### ISSUE TITLE
Loading/Checking Blocks/Chunks Asynchronously

### ISSUE THREAD

**Issue by gabizou** [EdificeMC/Edifice#5]
Currently, there is a little trouble with Sponge and this plugin where Timings will crash with the following:
```
[13:52:31] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_77]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_77]
	at co.aikar.util.JSONUtil.mapArray(JSONUtil.java:93) ~[JSONUtil.class:?]
	at co.aikar.timings.TimingHistory.lambda$new$4(TimingHistory.java:100) ~[TimingHistory.class:?]
	at co.aikar.util.JSONUtil.mapArrayToObject(JSONUtil.java:109) ~[JSONUtil.class:?]
	at co.aikar.timings.TimingHistory.<init>(TimingHistory.java:99) ~[TimingHistory.class:?]
	at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandler.java:101) ~[FullServerTickHandler.class:?]
	at net.minecraft.server.MinecraftServer.handler$onTickEnd$0(MinecraftServer.java:44) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:726) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:548) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
```
And the issue I'm willing to bet is that somewhere, this plugin is loading something asynchronously (or interacting with the world asynchronously), which is not supported and shouldn't be attempted in the first place.

I checked out the Structure saving as that could likely be the cause, but basically, loading this plugin on a 1.8.9 server after completing a blueprint will cause the server to crash.

**Comment by RobertHerhold** [comment]
Fixed in 57918726dd765b3349f073b486b64776841c5ac1
